### ISSUE TITLE
démarches simplifiées : questions sur l'outil

### ISSUE THREAD

**Issue by casvp** [betagouv/openfisca-paris#37]
@guillett 

Je suis très intéressée par l'outil "démarches simplifiées" dont tu m'as parlé tout à l'heure. Je vois qu'il fait la une des actualités sociales aujourd'hui. 

Je me questionne cependant sur plusieurs points  : 

comment peut-on aller chercher les données des impôts (ligne 14 de l'avis d'imposition) sans convention particulière avec les impôts, sans autorisation particulière ? Est-ce que c'est l'authentification par France Connect qui le permet ? 

L'outil démarches simplifiées est-il facilement interfaçable avec un logiciel d'instruction interne ?

**Comment by guillett** [comment]
Bonjour @casvp , voilà quelques éléments de réponse puis des éléments plus concrets pour avancer.

Nos discussions de lundi faisaient référence à plusieurs outils. Il y a

#### https://www.demarches-simplifiees.fr
pour permettre
- aux usagers de commencer la démarche,
- l'instruction des demandes et
- la récupération des informations par votre logiciel d'instruction interne.

#### http://particulier.api.gouv.fr
pour
- récupérer les informations automatiques auprès de la DGFIP grâce à la référence de l'avis et au numéro fiscal.

C'est grâce à l'API particulier que la _constractualisation_ avec la DGFIP est simplifiée.


### La suite
J'ai fait un premier test pour te montrer à quoi ça peut ressembler.

J'ai créé une procédure, accessible au usager pour commencer la démarche à la [page suivante]( https://www.demarches-simplifiees.fr/commencer/test-nam-declaratif-2).

Une partie de la forme peut être revue, c'est un test 🙂.

Y-a-t-il toutes les informations nécessaires à l'instruction de la demande ?
Comment est-il prévu de mettre à jour la carte de transport pour que les personnes puissent de déplacer gratuitement ?

**Comment by guillett** [comment]
Après discussion téléphonique, certaines clarifications ont été faites.

Pour les personnes n'ayant pas de carte Navigo, à la fin de l'instruction ces personnes recevront par la poste la carte chargée.

Pour les personnes ayant une carte navigo, leur carte sera mise à jour et chargée à partir :
- du premier du mois suivant si la demande est faite avant le lundi de la 3ème semaine ou bien
- du mois suivant si la demande est faite après cette date-là.

**Comment by guillett** [comment]
@casvp, Existe-t-il un formulaire papier pour cette future aide (si il existe) ?

Ma compréhension : l'instruction s'intéresse aux informations suivantes :
- Éligibilité de la personne
    - Age
        - Via l'avis d'imposition de [API Particulier](https://particulier.api.gouv.fr/tech/#impots)
    - Perception d'aides spécifiques
        - Déclaration sur l'honneur (en v1)
        - RNCPS en v2 ??
    - _Parisienneté_ (i.e. 3 ans de résidence sur Paris dans les 5 dernières années)
        - C'est compliqué…
        - Quittance sur 3 ans
        - Avis d'imposition ?
        - ???
- Régularité du séjour
        - Via l'avis d'imposition de [API Particulier](https://particulier.api.gouv.fr/tech/#impots)
- Éligibilité via l'impôts
    - Montant d'impôts
        - Via l'avis d'imposition de [API Particulier](https://particulier.api.gouv.fr/tech/#impots)

Y-a-t-il des informations manquantes ?

**Comment by casvp** [comment]
@guillett 

J'ai quelques précisions concernant la carte Navigo. Il y a trois étapes : 
* la carte est à demander auprès de la RATP
* les droits sont ouverts auprès du CASVP (nous leur demandons la photocopie du recto du pass navigo)
* 1 semaine après l'accord du CASVP, il est possible de charger la carte dans un guichet RATP

Il est donc nécessaire d'avoir déjà la carte Navigo lorsqu'on demande le NAM (qu'il s'agisse d'un renouvellement ou d'une première demande). 

Tu as bien fait le tour des informations nécessaires. il reste juste la photocopie du recto du Pass navigo qui fait partie des pièces justificatives demandées.

**Comment by guillett** [comment]
@casvp est-ce que cette photocopie peut être remplacée par la saisie du nom tel qu'écrit sur la carte et le numéro de la carte ?

**Comment by casvp** [comment]
On utilise cette copie de la carte Navigo pour plusieurs raisons : 
* reprendre le nom et prénom inscrits sur la carte (les noms et prénoms peuvent être différents des noms prénoms de la pièce d'identité). Si nous ne transmettons pas le nom tel qu'il est indiqué sur la carte, l'interface avec Comutitre ne se fera pas et la personne ne pourra activer sa carte. 
* s'assurer que c'est bien un navigo mois ou semaine. Nous ne prenons pas les autres formes de Navigo. 
* recopier le numéro du Pass navigo. 

Nous pouvons demander ces informations aux usagers mais en cas d'erreur, le pass ne pourra pas être activé et nous ne pourrons pas trouver la source de l'anomalie dans le dossier de l'usager (formulaire de demande et liste de pièces justificatives).

**Comment by guillett** [comment]
@casvp que penses-tu qu'on peut avoir comme objectif de demander les deux informations à l'usager (nom inscrit sur la carte et numéro de carte) et qu'une validation soit faite sur ce couple d'informations ?

L'erreur de recopie est autant existante coté instructeur et côté usager (voire l'erreur est peut-être plus grande côté instructeur car ils sont mieux intéressés par la finalité).

**Comment by casvp** [comment]
@guillett 

Oui éventuellement, cela pourrait être une solution. On pourrait demander le nom de naissance et prénom de la personne au début du questionnaire. Puis en fin de questionnaire, demander à l'usager de prendre sa carte Navigo et d'indiquer le nom, le prénom et le numéro tels qu'ils sont inscrits sur la carte. Pourrait-on imaginer une photo de la carte avec des champs à renseigner (nom-prénom-numéro) ?

**Comment by casvp** [comment]
@guillett 

https://www.paris.fr/services-et-infos-pratiques/aides-et-demarches/aides-allocations-et-subventions/aides-aux-transports-3848#navigo-emeraude-amethyste-seniors_10

Comme convenu, voici le lien du site Paris.fr vers l'aide NAM. Tu y trouveras toutes les informations sur l'aide, la liste de pièces justificatives nécessaires et le formulaire de demande.

**Comment by guillett** [comment]
demarches simplifiées ne sera pas utilisé. Je cloture.
